language: python

python:
  - "3.5"

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

before_install:
    - export WHEELHOUSE=$HOME/wheelhouse

install:
    - travis_retry pip install invoke
    - travis_retry invoke wheelhouse --develop
    - travis_retry invoke install --develop

env:
  - WATERBUTLER_CONFIG=./travis-config.json

script:
  - invoke test

before_cache:
  # exclude python requirements from github repo's
  - rm -f $HOME/wheelhouse/boto-*.whl
  - rm -f $HOME/wheelhouse/raven-*.whl

notifications:
  flowdock: 9f8a6baf3feafdb62e515718698d06d0
