language: python

python:
  - "3.5"

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

before_install:
    - export WHEELHOUSE=$HOME/wheelhouse

install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install wheel==0.26.0
    - travis_retry pip install invoke==0.11.1
    - travis_retry invoke wheelhouse --develop
    - travis_retry invoke install --develop

env:
  - WATERBUTLER_CONFIG=./travis-config.json

script:
  - invoke test

before_cache:
  # force reinstall for reqs pulled from github repos
  - rm -f $HOME/wheelhouse/boto-*.whl
  - rm -f $HOME/wheelhouse/aiohttpretty-*.whl


notifications:
  flowdock: 9f8a6baf3feafdb62e515718698d06d0
