version: "3"

services:
  wb_requirements:
    #image: quay.io/centerforopenscience/wb:develop
    #image: quay.io/centerforopenscience/wb:next
    image: wb:local
    command:
      - /bin/bash
      - -c
      - invoke install --develop &&
        (python -m compileall /usr/local/lib/python3.6 || true) &&
        rm -Rf /python3.6/* &&
        cp -Rf -p /usr/local/lib/python3.6 /
    restart: 'no'
    volumes:
      - wb_requirements_vol:/python3.6
      - wb_requirements_local_bin_vol:/usr/local/bin
      - wb-sync:/code:nocopy

  wb:
    #image: quay.io/centerforopenscience/wb:develop
    #image: quay.io/centerforopenscience/wb:next
    image: wb:local
    command: invoke server
    restart: unless-stopped
    ports:
      - 7777:7777
    env_file:
      - .docker-compose.wb.env
    volumes:
      - wb_requirements_vol:/usr/local/lib/python3.6
      - wb_requirements_local_bin_vol:/usr/local/bin
      - osfstoragecache_vol:/code/website/osfstoragecache
      - wb_tmp_vol:/tmp
      - wb-sync:/code:nocopy
    stdin_open: true

  worker:
    #image: quay.io/centerforopenscience/wb:develop
    #image: quay.io/centerforopenscience/wb:next
    image: wb:local
    command: invoke celery
    restart: unless-stopped
    depends_on:
      - wb
      - rabbitmq
    environment:
      C_FORCE_ROOT: 1
    env_file:
      - .docker-compose.wb.env
    volumes:
      - wb_requirements_vol:/usr/local/lib/python3.6
      - osfstoragecache_vol:/code/website/osfstoragecache
      - wb_tmp_vol:/tmp
      - wb-sync:/code:nocopy
    stdin_open: true

  # wb_flower:
  #   image: quay.io/centerforopenscience/wb:develop
  #   # Install flower here, instead of in WB repo, due to tornado version conflict
  #   command: [/bin/bash, -c, "pip install flower && celery flower -A waterbutler.tasks.app.app --port=5556 --broker=amqp://guest:guest@192.168.168.167:5672//"]
  #   depends_on:
  #     - rabbitmq
  #   # Use non-default port to avoid conflict with OSF flower
  #   ports:
  #     - 5556:5556

volumes:

  wb-sync:
    external: true
